/**
 * MuseService - Muse AI Music Generation Service
 * 
 * This service handles communication with Muse AI for descriptive command-based music generation.
 * Muse AI uses natural language commands (human-like-music-speech-commands) to generate music,
 * providing a more intuitive and flexible approach compared to structured parameters.
 * 
 * @module services/muse.service
 * @version 1.0.0
 * @author ZMusic Team
 */

import { config } from '../config/index.js';
import Logger from '../utils/logger.js';

/**
 * Logger instance for this service
 * @type {Logger}
 */
const logger = new Logger('MuseService');

/**
 * MuseService class - Handles Muse AI music generation
 * 
 * @class MuseService
 * @description Provides methods to generate music using Muse AI's natural language command system
 */
export class MuseService {
  /**
   * Creates an instance of MuseService
   * 
   * @constructor
   * @description Initializes the service with API key and base URL from configuration
   */
  constructor() {
    /**
     * API key for authentication
     * @type {string}
     * @private
     */
    this.apiKey = config.museApiKey;
    
    /**
     * Base URL for API endpoints
     * @type {string}
     * @private
     */
    this.baseUrl = config.museBaseUrl;
    
    logger.info('MuseService initialized successfully');
  }

  /**
   * Check if the service is properly configured
   * 
   * @method isConfigured
   * @description Validates that API key is present
   * @returns {boolean} True if API key is configured, false otherwise
   * 
   * @example
   * if (museService.isConfigured()) {
   *   // Proceed with Muse AI generation
   * } else {
   *   // Show configuration error
   * }
   */
  isConfigured() {
    return Boolean(this.apiKey && this.apiKey.length > 0);
  }

  /**
   * Generate a Muse AI descriptive command (human-like-music-speech-commands)
   * 
   * @method generateMuseCommand
   * @description Creates a natural language command string for Muse AI based on parameters
   * @param {Object} params - Command parameters
   * @param {string} [params.genre='流行'] - Music genre (e.g., '流行', '摇滚', '电子')
   * @param {string} [params.style='现代'] - Arrangement style (e.g., '现代', '古典', '实验')
   * @param {number} [params.bpm=122] - Beats per minute
   * @param {string} [params.theme='爱情'] - Song theme (e.g., '爱情', '梦想', '自然')
   * @param {string} [params.mood='温暖'] - Emotional mood (e.g., '温暖', '激昂', '忧郁')
   * @param {string} [params.elements='热带打击乐'] - Musical elements/instruments
   * @param {string} [params.subStyle='浩室'] - Sub-style within genre
   * @param {string} [params.subject='我'] - Song subject (who)
   * @param {string} [params.object='你'] - Song object (to whom)
   * @param {string} [params.verse='verse_1'] - Verse identifier
   * @param {number} [params.duration=60] - Target duration in seconds
   * @returns {string} Natural language command string for Muse AI
   * 
   * @example
   * const command = museService.generateMuseCommand({
   *   genre: '流行',
   *   bpm: 128,
   *   theme: '梦想',
   *   mood: '激昂',
   *   duration: 180
   * });
   * // Returns: "创作一首流行风格的歌曲, BPM 128, 主题为梦想..."
   */
  generateMuseCommand(params) {
    const {
      genre = '流行',
      style = '现代',
      bpm = 122,
      theme = '爱情',
      mood = '温暖',
      elements = '热带打击乐',
      subStyle = '浩室',
      subject = '我',
      object = '你',
      verse = 'verse_1',
      duration = 60
    } = params;

    return `创作一首${genre}风格的歌曲, BPM ${bpm}, 主题为${theme}, 情绪为${mood}, 包含${elements}, 子风格为${subStyle}, ${verse}段, 持续${duration}秒, 讲述${subject}对${object}的${theme}故事, 融合${style}编曲手法, 营造${mood}氛围。`;
  }

  /**
   * Generate music using Muse AI
   * 
   * @method generateMusic
   * @async
   * @description Submits a music generation request to Muse AI using natural language command
   * @param {string} museCommand - Natural language command generated by generateMuseCommand
   * @param {Object} [options={}] - Generation options
   * @param {number} [options.duration=60] - Target duration in seconds
   * @param {string} [options.style='auto'] - Style preference ('auto' for automatic)
   * @param {string} [options.quality='high'] - Output quality ('low', 'medium', 'high')
   * @returns {Promise<Object>} Generation result with taskId and status
   * @throws {Error} If API key is not configured or API request fails
   * 
   * @example
   * const command = museService.generateMuseCommand({ theme: '梦想' });
   * const result = await museService.generateMusic(command, { duration: 180 });
   * console.log('Task ID:', result.taskId);
   */
  async generateMusic(museCommand, options = {}) {
    if (!this.isConfigured()) {
      throw new Error('Muse AI API key not configured. Set MUSE_AI_API_KEY in .env file.');
    }

    logger.info(`Generating Muse music with command: ${museCommand.substring(0, 80)}...`);

    try {
      const response = await fetch(`${this.baseUrl}/generate`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${this.apiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          command: museCommand,
          duration: options.duration || 60,
          style: options.style || 'auto',
          quality: options.quality || 'high'
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        logger.error(`API Error: ${response.status} - ${errorText}`);
        throw new Error(`Muse API error: ${response.status}`);
      }

      const data = await response.json();
      logger.info('Muse music generation initiated');

      return {
        success: true,
        taskId: data.id || data.task_id || `muse_${Date.now()}`,
        status: 'generating',
        command: museCommand,
        audioUrl: data.audio_url || null
      };
    } catch (error) {
      logger.error(`Generation failed: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get the current status of the Muse service
   * 
   * @method getStatus
   * @description Returns configuration status and base URL
   * @returns {Object} Status object with configured flag and baseUrl
   * 
   * @example
   * const status = museService.getStatus();
   * console.log('Configured:', status.configured);
   * console.log('Base URL:', status.baseUrl);
   */
  getStatus() {
    return {
      configured: this.isConfigured(),
      baseUrl: this.baseUrl
    };
  }
}

/**
 * Default export - Singleton instance of MuseService
 * @type {MuseService}
 */
export default new MuseService();

